// Fallback mock job data used when fixture intake import is unavailable.
import type {
  AppSettings,
  DeliveryPackage,
  MappingRule,
  OutputPreset,
  SourceBundle,
  TranslationJob,
  TranslationModel,
} from "@/lib/types";

export const outputPresets: OutputPreset[] = [
  {
    id: "preset-tv-48k",
    name: "TV Episodic 48k",
    sampleRate: 48000,
    bitDepth: 24,
    pullMode: "none",
    includeReferenceVideo: true,
  },
  {
    id: "preset-feature-96k",
    name: "Feature Printmaster 96k",
    sampleRate: 96000,
    bitDepth: 24,
    pullMode: "pull_down",
    includeReferenceVideo: true,
  },
];

const baseMappingRules: MappingRule[] = [
  { id: "map-dx", sourceTrackRole: "DX", targetNuendoTrack: "DX_MAIN", condition: "Preserve production dialogue layout" },
  { id: "map-mx", sourceTrackRole: "MX", targetNuendoTrack: "MX_STEM", condition: "Map music stems by role" },
  { id: "map-fx", sourceTrackRole: "FX", targetNuendoTrack: "FX_STEM", condition: "Retain effects editorial ordering" },
];

const intakeBundle: SourceBundle = {
  id: "bundle-rh-e03-r4",
  stage: "intake",
  origin: "resolve",
  bundleName: "RH_E03_R4_INTAKE_v12",
  resolveProject: "Red Harbor",
  resolveTimelineVersion: "RH_E03_R4_LOCK_v12",
  importedAtIso: "2026-03-05T09:32:00.000Z",
  intakeAssets: [
    {
      id: "asset-aaf",
      stage: "intake",
      origin: "resolve",
      fileKind: "aaf",
      fileRole: "timeline_exchange",
      fileName: "RH_E03_R4_v12.aaf",
      pathHint: "incoming/RH_E03_R4_v12.aaf",
      status: "ready",
    },
    {
      id: "asset-edl",
      stage: "intake",
      origin: "resolve",
      fileKind: "edl",
      fileRole: "marker_export",
      fileName: "RH_E03_R4_markers.edl",
      pathHint: "incoming/markers.edl",
      status: "ready",
    },
    {
      id: "asset-marker-csv",
      stage: "intake",
      origin: "resolve",
      fileKind: "csv",
      fileRole: "marker_export",
      fileName: "RH_E03_R4_markers.csv",
      pathHint: "incoming/markers.csv",
      status: "ready",
    },
    {
      id: "asset-meta",
      stage: "intake",
      origin: "resolve",
      fileKind: "csv",
      fileRole: "metadata_export",
      fileName: "RH_E03_R4_metadata.csv",
      pathHint: "incoming/metadata.csv",
      status: "ready",
    },
    {
      id: "asset-manifest",
      stage: "intake",
      origin: "resolve",
      fileKind: "json",
      fileRole: "delivery_manifest",
      fileName: "manifest.json",
      pathHint: "incoming/manifest.json",
      status: "ready",
    },
    {
      id: "asset-readme",
      stage: "intake",
      origin: "resolve",
      fileKind: "txt",
      fileRole: "delivery_readme",
      fileName: "README_IMPORT.txt",
      pathHint: "incoming/README_IMPORT.txt",
      status: "ready",
    },
    {
      id: "asset-ref",
      stage: "intake",
      origin: "resolve",
      fileKind: "mov",
      fileRole: "reference_video",
      fileName: "RH_E03_R4_ref.mov",
      pathHint: "incoming/ref.mov",
      status: "ready",
    },
    {
      id: "asset-field-recorder-report",
      stage: "intake",
      origin: "conform-bridge",
      fileKind: "csv",
      fileRole: "field_recorder_report",
      fileName: "RH_E03_R4_field_recorder_report.csv",
      pathHint: "incoming/field_recorder_report.csv",
      status: "ready",
    },
  ],
};

const translationModel: TranslationModel = {
  id: "model-rh-e03-r4",
  stage: "canonical",
  sourceBundleId: intakeBundle.id,
  timeline: {
    id: "tl-rh-e03-r4",
    name: "RH_E03_R4_LOCK_v12",
    startTimecode: "01:00:00:00",
    durationTimecode: "00:47:32:10",
    startFrame: 86314,
    durationFrames: 68362,
    fps: 23.976,
    sampleRate: 48000,
    dropFrame: false,
    markers: [
      { id: "mk-01", timelineTc: "01:08:12:00", timelineFrame: 98124, label: "ADR NOTE SC15", color: "yellow" },
      { id: "mk-02", timelineTc: "01:10:03:19", timelineFrame: 100799, label: "FX SWELL OUT", color: "blue" },
    ],
    tracks: [
      {
        id: "trk-dx1",
        name: "DX A",
        role: "DX",
        clips: [
          {
            id: "evt-001",
            recordIn: "01:08:11:12",
            recordOut: "01:08:18:02",
            sourceIn: "10:41:02:14",
            sourceOut: "10:41:09:04",
            recordInFrames: 98112,
            recordOutFrames: 98274,
            sourceInFrames: 924302,
            sourceOutFrames: 924464,
            clipName: "A102C008_230915",
            sourceFileName: "SC15_TK03_20260304.BWF",
            reel: "R4",
            tape: "SR152",
            scene: "15",
            take: "3",
            eventDescription: "Principal DX, café interior.",
            clipNotes: "Boom + lav blend candidate.",
            sourceAssetId: "in-bwf-1",
            channelCount: 6,
            channelLayout: "L,R,C,LFE,Ls,Rs",
            isPolyWav: true,
            hasBwf: true,
            hasIXml: true,
            isOffline: false,
            isNested: false,
            isFlattened: true,
            hasSpeedEffect: false,
            hasFadeIn: true,
            hasFadeOut: true,
          },
        ],
      },
      {
        id: "trk-fx1",
        name: "FX A",
        role: "FX",
        clips: [
          {
            id: "evt-002",
            recordIn: "01:08:22:08",
            recordOut: "01:08:32:17",
            sourceIn: "08:10:17:20",
            sourceOut: "08:10:28:05",
            recordInFrames: 98368,
            recordOutFrames: 98617,
            sourceInFrames: 705420,
            sourceOutFrames: 705669,
            clipName: "BG_STREET_RAIN",
            sourceFileName: "RAIN_WILDTRACK_02.WAV",
            reel: "R4",
            scene: "15",
            eventDescription: "Exterior rain bed under dialogue.",
            clipNotes: "Missing scene/take in source metadata.",
            sourceAssetId: "in-wav-2",
            channelCount: 2,
            channelLayout: "L,R",
            isPolyWav: false,
            hasBwf: false,
            hasIXml: false,
            isOffline: false,
            isNested: false,
            isFlattened: true,
            hasSpeedEffect: false,
            hasFadeIn: false,
            hasFadeOut: true,
          },
        ],
      },
    ],
  },
};

const deliveryPackage: DeliveryPackage = {
  id: "delivery-rh-e03-r4",
  stage: "delivery",
  target: "nuendo",
  packageName: "RH_E03_R4_NUENDO_v1",
  outputPresetId: outputPresets[0].id,
  artifacts: [
    {
      id: "out-aaf",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "aaf",
      fileRole: "timeline_exchange",
      fileName: "RH_E03_R4_NUENDO.aaf",
      pathHint: "delivery/RH_E03_R4_NUENDO.aaf",
      status: "queued",
    },
    {
      id: "out-marker-edl",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "edl",
      fileRole: "marker_export",
      fileName: "RH_E03_R4_MARKERS.edl",
      pathHint: "delivery/RH_E03_R4_MARKERS.edl",
      status: "queued",
    },
    {
      id: "out-marker-csv",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "csv",
      fileRole: "marker_export",
      fileName: "RH_E03_R4_MARKERS.csv",
      pathHint: "delivery/RH_E03_R4_MARKERS.csv",
      status: "queued",
    },
    {
      id: "out-meta-csv",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "csv",
      fileRole: "metadata_export",
      fileName: "RH_E03_R4_METADATA.csv",
      pathHint: "delivery/RH_E03_R4_METADATA.csv",
      status: "queued",
    },
    {
      id: "out-manifest",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "json",
      fileRole: "delivery_manifest",
      fileName: "manifest.json",
      pathHint: "delivery/manifest.json",
      status: "queued",
    },
    {
      id: "out-readme",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "txt",
      fileRole: "delivery_readme",
      fileName: "README_IMPORT.txt",
      pathHint: "delivery/README_IMPORT.txt",
      status: "queued",
    },
    {
      id: "out-field-recorder",
      stage: "delivery",
      origin: "conform-bridge",
      fileKind: "csv",
      fileRole: "field_recorder_report",
      fileName: "RH_E03_R4_FIELD_RECORDER_REPORT.csv",
      pathHint: "delivery/RH_E03_R4_FIELD_RECORDER_REPORT.csv",
      status: "queued",
    },
  ],
};

export const translationJobs: TranslationJob[] = [
  {
    id: "job-2403-e03-r4",
    jobName: "E03 Reel 4 Final Mix Prep",
    status: "needs_review",
    createdAtIso: "2026-03-05T09:34:00.000Z",
    updatedAtIso: "2026-03-05T09:51:00.000Z",
    sourceBundle: intakeBundle,
    translationModel,
    mappingRules: baseMappingRules,
    fieldRecorderCandidates: [
      {
        id: "frc-01",
        clipEventId: "evt-001",
        candidateFile: "SC15_TK03_20260304.BWF",
        matchScore: 98,
        strategy: "scene_take",
        matched: true,
      },
      {
        id: "frc-02",
        clipEventId: "evt-002",
        candidateFile: "RAIN_WILDTRACK_02.WAV",
        matchScore: 61,
        strategy: "filename_tc",
        matched: false,
      },
    ],
    preservationIssues: [
      {
        id: "pi-01",
        category: "downgraded",
        severity: "warning",
        scope: "track",
        title: "5.1 bus remap required",
        description: "Resolve DX 5.1 layout mapped to Nuendo 5.1 Film bus with channel order normalization.",
        sourceLocation: "Track DX A",
        targetArtifactId: "out-aaf",
        targetArtifactName: "RH_E03_R4_NUENDO.aaf",
        recommendedAction: "Verify fold-down matrix in Nuendo template before premix.",
      },
      {
        id: "pi-02",
        category: "manual-review",
        severity: "warning",
        scope: "clip",
        title: "Missing iXML scene/take metadata",
        description: "Event evt-002 lacks embedded scene/take data; fallback metadata was inferred.",
        sourceLocation: "Clip BG_STREET_RAIN",
        targetArtifactName: "RH_E03_R4_FIELD_RECORDER_REPORT.csv",
        recommendedAction: "Confirm field recorder match in Field Recorder tab.",
      },
    ],
    reconformChanges: [],
    analysisReport: {
      tracksTotal: 2,
      clipsTotal: 2,
      markersTotal: 2,
      offlineAssetsTotal: 0,
      highRiskCount: 0,
      warningCount: 2,
      blockedCount: 0,
      intakeCompletenessSummary: "Intake package complete: timeline exchange, markers, metadata, reference video, and production audio present.",
      deliveryReadinessSummary: "Delivery package can be assembled after manual review of one field recorder metadata fallback.",
    },
    outputPreset: outputPresets[0],
    deliveryPackage,
  },
];

export const templateMappingRules: MappingRule[] = baseMappingRules;

export const appSettings: AppSettings = {
  density: "compact",
  defaultPresetId: "preset-tv-48k",
  showFrameCounts: true,
};
